"""fix-things

Revision ID: 17b6b94de49c
Revises: 7b661bcee368
Create Date: 2024-11-16 11:55:48.044025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17b6b94de49c'
down_revision: Union[str, None] = '7b661bcee368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_fragments', sa.Column('hierarchy_meta', sa.JSON(), nullable=True))
    op.drop_column('document_fragments', 'fragment_meta')
    op.add_column('documents', sa.Column('tsv_content', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(filename, '')), 'A') || setweight(to_tsvector('english', coalesce(summary, '')), 'B')", persisted=True), nullable=True))
    op.create_index('ix_documents_tsv_content', 'documents', ['tsv_content'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_tsv_content', table_name='documents', postgresql_using='gin')
    op.drop_column('documents', 'tsv_content')
    op.add_column('document_fragments', sa.Column('fragment_meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('document_fragments', 'hierarchy_meta')
    # ### end Alembic commands ###
