"""make fields nullable

Revision ID: 697d6f8e0a30
Revises: a26bf7b7226d
Create Date: 2024-11-02 22:41:34.042131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '697d6f8e0a30'
down_revision: Union[str, None] = 'a26bf7b7226d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_fragments', 'fragment_content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('document_fragments', 'fragment_content_tsv',
               existing_type=postgresql.TSVECTOR(),
               nullable=True)
    op.alter_column('document_fragments', 'vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_fragments', 'vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               nullable=False)
    op.alter_column('document_fragments', 'fragment_content_tsv',
               existing_type=postgresql.TSVECTOR(),
               nullable=False)
    op.alter_column('document_fragments', 'fragment_content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
