"""try array approach to hierarchy

Revision ID: 7b661bcee368
Revises: 697d6f8e0a30
Create Date: 2024-11-03 17:15:06.824531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b661bcee368'
down_revision: Union[str, None] = '697d6f8e0a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_fragments', sa.Column('fragment_meta', sa.JSON(), nullable=True))
    op.alter_column('document_fragments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index('idx_fragment_document', 'document_fragments', ['document_id'], unique=False)
    op.add_column('documents', sa.Column('path_array', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('documents', sa.Column('hierarchy_meta', sa.JSON(), nullable=True))
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index('idx_document_filepath', 'documents', ['filepath'], unique=False)
    op.create_index('idx_document_path_array', 'documents', ['path_array'], unique=False, postgresql_using='gin')

    # Then we can safely drop file_content
    op.drop_column('documents', 'file_content')

    # Update existing rows (assuming you want to split the existing path by '/')
    op.execute("""
        UPDATE documents
        SET path_array = string_to_array(filepath, '/')
        WHERE path_array IS NULL
    """)

    # Then make it not nullable
    op.alter_column('documents', 'path_array',
                    existing_type=postgresql.ARRAY(sa.String()),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index('idx_document_path_array', table_name='documents', postgresql_using='gin')
    op.drop_index('idx_document_filepath', table_name='documents')
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('documents', 'hierarchy_meta')
    op.drop_column('documents', 'path_array')
    op.drop_index('idx_fragment_document', table_name='document_fragments')
    op.alter_column('document_fragments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('document_fragments', 'fragment_meta')
    # ### end Alembic commands ###
