"""Add document summaries

Revision ID: 820bb131ca84
Revises: a1a10e5b3cb2
Create Date: 2024-06-09 21:13:14.626230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '820bb131ca84'
down_revision: Union[str, None] = 'a1a10e5b3cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'summary')
    # ### end Alembic commands ###
