"""Refactor to Document and DocumentFragment

Revision ID: a1a10e5b3cb2
Revises: bbd7baf2ad29
Create Date: 2024-06-09 17:11:41.429957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'a1a10e5b3cb2'
down_revision: Union[str, None] = 'bbd7baf2ad29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('file_content', sa.Text(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.Vector(dim=768), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    op.create_table('document_fragments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('fragment_content', sa.Text(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.Vector(dim=768), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('code_files')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filepath', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vector', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='code_files_pkey')
    )
    op.drop_table('document_fragments')
    op.drop_table('documents')
    # ### end Alembic commands ###
