"""initial migration

Revision ID: a26bf7b7226d
Revises:
Create Date: 2024-11-02 22:09:55.525558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'a26bf7b7226d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('file_content', sa.Text(), nullable=False),
    sa.Column('tsv_content', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(filename, '')), 'A') || setweight(to_tsvector('english', coalesce(summary, '')), 'B') || setweight(to_tsvector('english', coalesce(file_content, '')), 'C')", ), nullable=True),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    op.create_index('ix_documents_tsv_content', 'documents', ['tsv_content'], unique=False, postgresql_using='gin')
    op.create_table('document_fragments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('fragment_content', sa.Text(), nullable=False),
    sa.Column('fragment_content_tsv', postgresql.TSVECTOR(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_fragments_fragment_content_tsv', 'document_fragments', ['fragment_content_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_document_fragments_summary_tsv', 'document_fragments', ['summary_tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_fragments_summary_tsv', table_name='document_fragments', postgresql_using='gin')
    op.drop_index('ix_document_fragments_fragment_content_tsv', table_name='document_fragments', postgresql_using='gin')
    op.drop_table('document_fragments')
    op.drop_index('ix_documents_tsv_content', table_name='documents', postgresql_using='gin')
    op.drop_table('documents')
    # ### end Alembic commands ###
