"""index fragment_content_tsv

Revision ID: b592c2b7dd26
Revises: d25a39fde9d4
Create Date: 2024-11-16 22:02:06.028121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b592c2b7dd26'
down_revision: Union[str, None] = 'd25a39fde9d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_document_fragments_tsv_content', 'document_fragments', ['fragment_content_tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_fragments_tsv_content', table_name='document_fragments', postgresql_using='gin')
    # ### end Alembic commands ###
