"""Add filename TSVECTOR column and GIN index

Revision ID: df29e8ab4adf
Revises: e86d89f52ec0
Create Date: 2024-06-19 16:55:46.611847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df29e8ab4adf'
down_revision: Union[str, None] = 'e86d89f52ec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filename_tsv', postgresql.TSVECTOR(), nullable=True))

    connection = op.get_bind()
    connection.execute(
        text("UPDATE documents SET filename_tsv = to_tsvector('english', filename)")
    )

    op.create_index('ix_documents_filename_tsv', 'documents', ['filename_tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_filename_tsv', table_name='documents', postgresql_using='gin')
    op.drop_column('documents', 'filename_tsv')
    # ### end Alembic commands ###
