"""Add TSVECTOR columns and GIN indexes

Revision ID: e86d89f52ec0
Revises: e380f16584ef
Create Date: 2024-06-19 16:29:06.481356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e86d89f52ec0'
down_revision: Union[str, None] = 'e380f16584ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('document_fragments', sa.Column('fragment_content_tsv', postgresql.TSVECTOR(), nullable=True))
    op.add_column('document_fragments', sa.Column('summary_tsv', postgresql.TSVECTOR(), nullable=True))
    op.add_column('documents', sa.Column('file_content_tsv', postgresql.TSVECTOR(), nullable=True))
    op.add_column('documents', sa.Column('summary_tsv', postgresql.TSVECTOR(), nullable=True))
    
    # Populate TSVECTOR columns with existing data
    connection = op.get_bind()
    connection.execute(
        text("UPDATE documents SET file_content_tsv = to_tsvector('english', file_content)")
    )
    connection.execute(
        text("UPDATE documents SET summary_tsv = to_tsvector('english', summary)")
    )
    connection.execute(
        text("UPDATE document_fragments SET fragment_content_tsv = to_tsvector('english', fragment_content)")
    )
    connection.execute(
        text("UPDATE document_fragments SET summary_tsv = to_tsvector('english', summary)")
    )
    
    op.create_index('ix_document_fragments_fragment_content_tsv', 'document_fragments', ['fragment_content_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_document_fragments_summary_tsv', 'document_fragments', ['summary_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_documents_file_content_tsv', 'documents', ['file_content_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_documents_summary_tsv', 'documents', ['summary_tsv'], unique=False, postgresql_using='gin')
    
    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_summary_tsv', table_name='documents', postgresql_using='gin')
    op.drop_index('ix_documents_file_content_tsv', table_name='documents', postgresql_using='gin')
    op.drop_column('documents', 'summary_tsv')
    op.drop_column('documents', 'file_content_tsv')
    op.drop_index('ix_document_fragments_summary_tsv', table_name='document_fragments', postgresql_using='gin')
    op.drop_index('ix_document_fragments_fragment_content_tsv', table_name='document_fragments', postgresql_using='gin')
    op.drop_column('document_fragments', 'summary_tsv')
    op.drop_column('document_fragments', 'fragment_content_tsv')
    # ### end Alembic commands ###
